language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
os:
  - linux
  - osx

before_script:
  - rustup target add arm-linux-androideabi
  - rustup target add armv7-linux-androideabi
  - rustup target add aarch64-linux-android
  - rustup target add i686-linux-android

script:
  - cargo check --target=arm-linux-androideabi
  - cargo check --target=armv7-linux-androideabi
  - cargo check --target=aarch64-linux-android
  - cargo check --target=i686-linux-android
  - cargo doc
  - cargo test
